from django.urls import path
from rest_framework_simplejwt.views import TokenObtainPairView, TokenRefreshView

from .views import (
    HealthView,
    JobRoleListCreateView,
    ProfileView,
    ResumeAnalysisListView,
    ResumeDetailView,
    ResumeParseView,
    ResumeListCreateView,
    RunAnalysisView,
    SignupView,
    TailorResumeView,
    OptimizeResumeQualityView,
    ExportAtsPdfLocalView,
    AutofillAnswersView,
    TailoredJobRunListView,
    ProfileConfigView,
    ApplicationTrackingListCreateView,
    ApplicationTrackingDetailView,
    CompanyListCreateView,
    CompanyDetailView,
    EmployeeListCreateView,
    EmployeeDetailView,
    JobListCreateView,
    JobDetailView,
)

urlpatterns = [
    path('health/', HealthView.as_view()),
    path('signup/', SignupView.as_view()),
    path('parse-resume/', ResumeParseView.as_view()),
    path('token/', TokenObtainPairView.as_view()),
    path('token/refresh/', TokenRefreshView.as_view()),
    path('profile/', ProfileView.as_view()),
    path('profile-config/', ProfileConfigView.as_view()),
    path('job-roles/', JobRoleListCreateView.as_view()),
    path('resumes/', ResumeListCreateView.as_view()),
    path('resumes/<int:resume_id>/', ResumeDetailView.as_view()),
    path('analyses/', ResumeAnalysisListView.as_view()),
    path('run-analysis/', RunAnalysisView.as_view()),
    path('tailor-resume/', TailorResumeView.as_view()),
    path('optimize-resume-quality/', OptimizeResumeQualityView.as_view()),
    path('export-ats-pdf-local/', ExportAtsPdfLocalView.as_view()),
    path('autofill-answers/', AutofillAnswersView.as_view()),
    path('tailored-job-runs/', TailoredJobRunListView.as_view()),
    path('tracking/', ApplicationTrackingListCreateView.as_view()),
    path('tracking/<int:tracking_id>/', ApplicationTrackingDetailView.as_view()),
    path('companies/', CompanyListCreateView.as_view()),
    path('companies/<int:company_id>/', CompanyDetailView.as_view()),
    path('employees/', EmployeeListCreateView.as_view()),
    path('employees/<int:employee_id>/', EmployeeDetailView.as_view()),
    path('jobs/', JobListCreateView.as_view()),
    path('jobs/<int:job_id>/', JobDetailView.as_view()),
]
