from django.urls import path
from rest_framework_simplejwt.views import TokenObtainPairView, TokenRefreshView

from .views import (
    HealthView,
    ProfileView,
    ProfileInfoView,
    ProfilePanelListCreateView,
    ProfilePanelDetailView,
    ResumeDetailView,
    ResumeParseView,
    ResumeListCreateView,
    TailoredResumeListCreateView,
    SignupView,
    TailorResumeView,
    OptimizeResumeQualityView,
    ExportAtsPdfLocalView,
    AutofillAnswersView,
    ProfileConfigView,
    ApplicationTrackingListCreateView,
    ApplicationTrackingDetailView,
    ApplicationTrackingMailTestView,
    CompanyListCreateView,
    CompanyDetailView,
    EmployeeListCreateView,
    EmployeeDetailView,
    JobListCreateView,
    JobDetailView,
    BulkUploadEmployeesView,
    BulkUploadJobsView,
    ExtensionFormMetaView,
    ExtensionCompanySearchView,
    ExtensionJobCreateView,
    ExtensionEmployeeCreateView,
    TemplateListCreateView,
    TemplateDetailView,
    SubjectTemplateListCreateView,
    SubjectTemplateDetailView,
    AchievementListCreateView,
    AchievementDetailView,
    InterviewListCreateView,
    InterviewDetailView,
    LocationListView,
)

urlpatterns = [
    path('health/', HealthView.as_view()),
    path('signup/', SignupView.as_view()),
    path('parse-resume/', ResumeParseView.as_view()),
    path('token/', TokenObtainPairView.as_view()),
    path('token/refresh/', TokenRefreshView.as_view()),
    path('profile/', ProfileView.as_view()),
    path('profile-info/', ProfileInfoView.as_view()),
    path('profile-panels/', ProfilePanelListCreateView.as_view()),
    path('profile-panels/<int:panel_id>/', ProfilePanelDetailView.as_view()),
    path('profile-config/', ProfileConfigView.as_view()),
    path('templates/', TemplateListCreateView.as_view()),
    path('templates/<int:template_id>/', TemplateDetailView.as_view()),
    path('subject-templates/', SubjectTemplateListCreateView.as_view()),
    path('subject-templates/<int:subject_template_id>/', SubjectTemplateDetailView.as_view()),
    path('achievements/', AchievementListCreateView.as_view()),
    path('achievements/<int:achievement_id>/', AchievementDetailView.as_view()),
    path('interviews/', InterviewListCreateView.as_view()),
    path('interviews/<int:interview_id>/', InterviewDetailView.as_view()),
    path('locations/', LocationListView.as_view()),
    path('resumes/', ResumeListCreateView.as_view()),
    path('tailored-resumes/', TailoredResumeListCreateView.as_view()),
    path('resumes/<int:resume_id>/', ResumeDetailView.as_view()),
    path('tailor-resume/', TailorResumeView.as_view()),
    path('optimize-resume-quality/', OptimizeResumeQualityView.as_view()),
    path('export-ats-pdf-local/', ExportAtsPdfLocalView.as_view()),
    path('autofill-answers/', AutofillAnswersView.as_view()),
    path('tracking/', ApplicationTrackingListCreateView.as_view()),
    path('tracking/<int:tracking_id>/', ApplicationTrackingDetailView.as_view()),
    path('tracking/<int:tracking_id>/mail-test/', ApplicationTrackingMailTestView.as_view()),
    path('companies/', CompanyListCreateView.as_view()),
    path('companies/<int:company_id>/', CompanyDetailView.as_view()),
    path('employees/', EmployeeListCreateView.as_view()),
    path('employees/<int:employee_id>/', EmployeeDetailView.as_view()),
    path('jobs/', JobListCreateView.as_view()),
    path('jobs/<int:job_id>/', JobDetailView.as_view()),
    path('bulk-upload/employees/', BulkUploadEmployeesView.as_view()),
    path('bulk-upload/jobs/', BulkUploadJobsView.as_view()),
    path('extension/form-meta/', ExtensionFormMetaView.as_view()),
    path('extension/companies/', ExtensionCompanySearchView.as_view()),
    path('extension/jobs/', ExtensionJobCreateView.as_view()),
    path('extension/employees/', ExtensionEmployeeCreateView.as_view()),
]
