# Generated by Codex on 2026-04-18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def backfill_job_created_by(apps, schema_editor):
    Job = apps.get_model('analyzer', 'Job')
    for row in Job.objects.select_related('company__profile__user').all():
        company = getattr(row, 'company', None)
        profile = getattr(company, 'profile', None) if company is not None else None
        owner_id = getattr(profile, 'user_id', None)
        if owner_id and row.created_by_id != owner_id:
            row.created_by_id = owner_id
            row.save(update_fields=['created_by'])


class Migration(migrations.Migration):

    dependencies = [
        ('analyzer', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='assigned_to',
            field=models.ManyToManyField(blank=True, related_name='assigned_jobs', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='job',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_jobs', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterModelOptions(
            name='job',
            options={
                'ordering': ['-date_of_posting', '-created_at'],
                'permissions': [('view_all_job', 'Can view all job records')],
            },
        ),
        migrations.RunPython(backfill_job_created_by, migrations.RunPython.noop),
    ]
