# Generated by Django 6.0.4 on 2026-04-18 20:57

import django.db.models.deletion
import django.db.models.functions.text
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analyzer', '0006_delete_workspacemember'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubjectTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=220)),
                ('category', models.CharField(choices=[('personalized', 'Personalized'), ('follow_up', 'Follow Up'), ('opening', 'Opening'), ('experience', 'Experience'), ('closing', 'Closing'), ('general', 'General')], default='general', max_length=20)),
                ('subject', models.CharField(max_length=255)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subject_templates', to='analyzer.userprofile')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['profile', '-created_at'], name='analyzer_su_profile_ef112a_idx')],
                'constraints': [models.UniqueConstraint(django.db.models.functions.text.Lower('name'), models.F('profile'), name='uniq_subject_template_profile_name_ci')],
            },
        ),
    ]
