# Generated by Django 6.0.4 on 2026-04-18 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analyzer', '0007_subjecttemplate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subjecttemplate',
            name='category',
            field=models.CharField(choices=[('fresh', 'Fresh'), ('follow_up', 'Follow Up')], default='fresh', max_length=20),
        ),
    ]
