# Generated by Codex on 2026-04-22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analyzer', '0011_remove_dummy_user_concept'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subjecttemplate',
            name='template_scope',
        ),
        migrations.AlterField(
            model_name='subjecttemplate',
            name='profile',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name='subject_templates',
                to='analyzer.userprofile',
            ),
        ),
    ]
